plugins {
    id 'com.android.application'
}

android {
    namespace 'com.lucis.tv'
    compileSdk 34

    defaultConfig {
        applicationId 'com.lucis.tv'
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName '0.1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
